# Generated by Django 4.2.16 on 2024-11-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_stock_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=50, unique=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('da_xoa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=30, unique=True)),
                ('so_luong', models.IntegerField(default=1)),
                ('da_xoa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
            },
        ),
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
