# Generated by Django 4.2.16 on 2024-11-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_danhmuc_tonkho_remove_stock_category_delete_category'),
        ('transactions', '0010_nhacungcap_phieubanhang_phieunhapkho_sanphamban_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='tonkho',
            name='danh_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ton_khos', to='inventory.danhmuc'),
        ),
    ]
