# Generated by Django 5.1.3 on 2024-11-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_hosonguoidung'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HoSoNguoiDung',
        ),
    ]
