# Generated by Django 5.1.3 on 2024-12-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_delete_hosonguoidung'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonkho',
            name='gia_nhap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tonkho',
            name='han_su_dung',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tonkho',
            name='ngay_cap_nhat_cuoi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tonkho',
            name='so_luong',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tonkho',
            name='ten',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
