# Generated by Django 5.1.3 on 2024-12-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_tonkho_gia_nhap_tonkho_han_su_dung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonkho',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
