# Generated by Django 5.1.3 on 2024-12-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_tonkho_hinh_anh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tonkho',
            name='gia_nhap',
        ),
        migrations.RemoveField(
            model_name='tonkho',
            name='han_su_dung',
        ),
        migrations.RemoveField(
            model_name='tonkho',
            name='ngay_cap_nhat_cuoi',
        ),
    ]
