# Generated by Django 5.1.3 on 2024-11-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_exporttransaction_importtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importtransaction',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='importtransaction',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='ExportTransaction',
        ),
        migrations.DeleteModel(
            name='ImportTransaction',
        ),
    ]
