# Generated by Django 5.1.3 on 2024-11-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_importtransaction_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salebill',
            old_name='gstin',
            new_name='tax_id',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='gstin',
            new_name='tax_id',
        ),
    ]
