# Generated by Django 5.1.3 on 2024-11-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_gstin_salebill_tax_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salebill',
            old_name='tax_id',
            new_name='gstin',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='tax_id',
            new_name='gstin',
        ),
    ]
