# Generated by Django 4.2.16 on 2024-11-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_tax_id_salebill_gstin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='gstin',
        ),
    ]
