# Generated by Django 4.2.16 on 2024-11-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_salebill_gstin_remove_supplier_gstin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='total',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='total',
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_of_measurement',
            field=models.CharField(default='Chiếc', max_length=50),
        ),
    ]
