# Generated by Django 4.2.16 on 2024-11-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_purchasebilldetails_cess_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebilldetails',
            name='billno',
        ),
        migrations.DeleteModel(
            name='PurchaseBillDetails',
        ),
        migrations.DeleteModel(
            name='SaleBillDetails',
        ),
    ]
