# Generated by Django 4.2.16 on 2024-11-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_danhmuc_tonkho_remove_stock_category_delete_category'),
        ('transactions', '0009_remove_salebilldetails_billno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=150)),
                ('so_dien_thoai', models.CharField(max_length=12, unique=True)),
                ('dia_chi', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('da_xoa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuBanHang',
            fields=[
                ('so_phieu', models.AutoField(primary_key=True, serialize=False)),
                ('thoi_gian', models.DateTimeField(auto_now=True)),
                ('ten_nguoi_mua', models.CharField(max_length=150)),
                ('so_dien_thoai', models.CharField(max_length=12)),
                ('dia_chi', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('so_phieu', models.AutoField(primary_key=True, serialize=False)),
                ('thoi_gian', models.DateTimeField(auto_now=True)),
                ('giam_gia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhapkho_nhacungcap', to='transactions.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='SanPhamBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('don_gia', models.IntegerField(default=1)),
                ('thanh_tien', models.IntegerField(default=1)),
                ('phieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieuban', to='transactions.phieubanhang')),
                ('ton_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanpham_ban', to='inventory.tonkho')),
            ],
        ),
        migrations.CreateModel(
            name='SanPhamNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('don_gia', models.IntegerField(default=1)),
                ('phan_tram_chiet_khau', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('don_vi_tinh', models.CharField(default='Chiếc', max_length=50)),
                ('thanh_tien', models.IntegerField(default=1)),
                ('phieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieunhap', to='transactions.phieunhapkho')),
                ('ton_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanpham_nhap', to='inventory.tonkho')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='stock',
        ),
        migrations.DeleteModel(
            name='PurchaseBill',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='SaleBill',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
