# Generated by Django 4.2.16 on 2024-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_nhacungcap_phieubanhang_phieunhapkho_sanphamban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanphamban',
            name='phan_tram_chiet_khau',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sanphamban',
            name='thanh_tien',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
