# Generated by Django 5.1.3 on 2024-12-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_phieubanhang_user_phieunhapkho_user_sanphamban_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanphamnhapkho',
            name='han_su_dung',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanphamnhapkho',
            name='ma_lo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
