# Generated by Django 5.1.3 on 2024-12-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_sanphamnhapkho_han_su_dung_sanphamnhapkho_ma_lo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanphamnhapkho',
            name='ma_lo',
        ),
    ]
