# Generated by Django 5.1.3 on 2024-12-10 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_remove_sanphamnhapkho_ma_lo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanphamban',
            name='thoi_gian',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanphamnhapkho',
            name='thoi_gian',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
